version: "3.1"
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: nodepassword
      POSTGRES_DB: nodeapp
    ports:
      - "3000:3000"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: